### ISSUE TITLE
Add braces if required

### ISSUE THREAD

**Issue by AgentFire** [cincuranet/ConfigureAwaitChecker#11]
This code

    var releaser = await (Task<AsyncSemaphore.Releaser>)finished;

Works fine, yet fairly suggests to add `ConfigureAwait(false)` call. But when you open Quick Actions (Ctrl+.) and apply the suggestion, it turns in to this:

    var releaser = await (Task<AsyncSemaphore.Releaser>)finished.ConfigureAwait(false);

Which won't compile (obviously).

Instead, it should add braces:

    var releaser = await ((Task<AsyncSemaphore.Releaser>)finished).ConfigureAwait(false);

**Comment by cincuranet** [comment]
Thanks for reporting this. I'll have a look.

**Comment by cincuranet** [comment]
Fixed in 709f5ce.
