### ISSUE TITLE
Add to single project but affects whole solution

### ISSUE THREAD

**Issue by bruno-garcia** [cincuranet/ConfigureAwaitChecker#12]
Firstly thank you for putting the effort into this!
I've added it to a single project in a solution but unfortunately the analysis is now solution wide.

All projects now see the lack of `ConfigureAwait(false)` as an error where in fact it could be an issue to make it so since recapture of synchronization context would be desired.

I'm unaware if this is a default behaviour of roslyn analizers though. If that's the case I guess I'd need to raise this on a separate repo.

**Comment by cincuranet** [comment]
This seems to be default behavior. Take a look at #7.

**Comment by bruno-garcia** [comment]
Yeah I was missing: `<PrivateAssets>all</PrivateAssets>`
Thanks!
