### ISSUE TITLE
Useless warning being emitted for System.Windows.Threading.Dispatcher 

### ISSUE THREAD

**Issue by BionicCode** [cincuranet/ConfigureAwaitChecker#13]
When invoking the System.Windows.Threading.Dispatcher the analyzer emits a warning. Because the Dispatcher object never returns a Task, the warning is rather annoying than helpful. 
For instance `await Application.Current.Dispatcher.InvokeAsync(OnMergeCompleted, DispatcherPriority.Background); ` generates a warning: Possibily missing 'ConfigureAwait(false)' call. The ID is just CongigureAwaitChecker. The reason for this is, that the Dispatcher object doesn't return a Task object by design, but the method ConfigureAwait(bool) is a member of Task.

**Comment by cincuranet** [comment]
Correct. In #10 some work is already available to take into account semantic part of the code. Although it needs more work (I have it already in the queue).

On the other hand in WPF project, where the `SynchronizationContext` matters, I don't think adding this analyzer makes much sense. It should be primarily in a library, etc.

**Comment by cincuranet** [comment]
Done in 3a3c1a38c2d9ce1a52e5121a8164fdfd83409eab.
