### ISSUE TITLE
Build Error in VS 2017 - Microsoft.CodeAnalysis mismatch

### ISSUE THREAD

**Issue by s-anurag** [cincuranet/ConfigureAwaitChecker#17]
```
Error	CS8032	An instance of analyzer ConfigureAwaitChecker.Analyzer.ConfigureAwaitCheckerAnalyzer cannot be created from 
_________\ConfigureAwaitChecker.Analyzer.2.0.0\analyzers\dotnet\cs\ConfigureAwaitChecker.Analyzer.dll :
 Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
```
I am running into this error while building with the nuget package installed. I also installed the latest version of Microsoft.CodeAnalysis but that doesn't help. Can you please help with this.

**Comment by cincuranet** [comment]
Can you share a project where it happens?

**Comment by s-anurag** [comment]
I am afraid I cannot share the project here but would that help if I can share the other dependencies for the project where I am seeing this error?

**Comment by cincuranet** [comment]
Sure. We can try that.

**Comment by s-anurag** [comment]
here is a sample packages.config -
```
  <package id="AsyncFixer" version="1.1.6" targetFramework="net452" developmentDependency="true" />
  <package id="ConfigureAwaitChecker.Analyzer" version="2.0.0" targetFramework="net452" />
  <package id="StyleCop.Analyzers" version="1.0.2" targetFramework="net472" developmentDependency="true" />
<package id="Newtonsoft.Json" version="9.0.1" targetFramework="net472" />
```

**Comment by s-anurag** [comment]
The issue is fixed now. the issue was with the latest version which was not compatible (.NET framework) with my project. So I am using the previous version - 1.0.1 which is working fine.
Thanks a lot for the quick response.
