### ISSUE TITLE
Add support for extension methods

### ISSUE THREAD

**Issue by YairHalberstadt** [cincuranet/ConfigureAwaitChecker#25]
Thank you for this analyzer - I find it very useful.

A number of custom awaitables do not implement ConfigureAwait even though they should (eg. GRPC's AsyncUnaryCall). The solution there is to add it as an extension method.

If you think it would be acceptable to warn when an extension ConfigureAwait is not called, I would be happy to implement it.

**Comment by cincuranet** [comment]
The problem I see, is that's it's not easy to discover extension methods for a given type. For #23 or #24 (which is on my todo), where it's implemented as an extension methods, it's easier, because it's known in advance where to look for. Do you have idea how to handle this?

**Comment by YairHalberstadt** [comment]
The way the compiler does it is literally to go through every accessible namespace and look for potential extension methods.

I could try doing that.

**Comment by YairHalberstadt** [comment]
It turned out to be rather simple: Just use LookupSymbols.
https://github.com/cincuranet/ConfigureAwaitChecker/pull/26

**Comment by cincuranet** [comment]
I'll continue in #26.
