### ISSUE TITLE
Disable for .Net Core projects

### ISSUE THREAD

**Issue by Gerboa** [cincuranet/ConfigureAwaitChecker#27]
I've added this as a VS Add-in and it reports for **all** solutions/projects that I load which is great, _but_ `ConfigureAwait` is not needed for .Net Core projects.

Can the check be disabled per project or turned off for **all** .Net Core projects?

**Comment by cincuranet** [comment]
Yes, you can disable in using various way on per-project basis. More info [here](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019).

Also it's not entirely true that it's not needed for .NET Core (and also .NET Standard). Depends where the code runs. I.e. WinForms/WPF on .NET Core 3.0+ still uses `SynchronizationContext`. While the ASP.NET Core does not now.
