### ISSUE TITLE
CAC002 reported wrong

### ISSUE THREAD

**Issue by chrfin** [cincuranet/ConfigureAwaitChecker#30]
I have the following code:

```c#
var devices = (await deviceManager.SearchConnectedDevicesAsync().ConfigureAwait(true)).Where(d => !d.IsInUse);
ComboBoxApiDevices.ItemsSource = devices;
```

This is marked with `CAC002: Possibly wrong ConfigureAwait(true) call`. But the next line accesses the GUI so `true` is correct.

Is this a bug of CAC or do I need to format my code differently?

**Comment by cincuranet** [comment]
It's not a bug. You shouldn't use this analyzer in UI parts of your solution.

**Comment by chrfin** [comment]
Ok, thanks for the info, didn't know that. Maybe this could be added as a note to the readme?

**Comment by cincuranet** [comment]
I think one needs to first understand reason for (not) using `ConfigureAwait(false)` and then he/she can successfully benefit from the analyzer.
