### ISSUE TITLE
Add license into nuget package ConfigureAwaitChecker.Analyzer

### ISSUE THREAD

**Issue by max-ieremenko** [cincuranet/ConfigureAwaitChecker#31]
Repository is under MIT license.

License in the [ConfigureAwaitChecker.Analyzer.nuspec](https://www.nuget.org/packages/ConfigureAwaitChecker.Analyzer/) is missing.
What is the license of the package, MIT?

**Comment by cincuranet** [comment]
Yes, the package is MIT too. Do you care to create PR?

**Comment by max-ieremenko** [comment]
The pull request [29 Add license to nuget packages](https://github.com/cincuranet/ConfigureAwaitChecker/pull/29) from **21.05.2021** already contains all required changes.

The nuget [ConfigureAwaitChecker.Analyzer](https://www.nuget.org/packages/ConfigureAwaitChecker.Analyzer/) was published last time on **11.03.2021**.

The matter is small - publish the latest version.

**Comment by cincuranet** [comment]
Ah, I see. I was waiting for some change to come by and then publish new version. Will bump the version and publish.

**Comment by cincuranet** [comment]
And done: https://www.nuget.org/packages/ConfigureAwaitChecker.Analyzer/5.0.0.1.
