### ISSUE TITLE
Any chance of a 1.0.0 release?

### ISSUE THREAD

**Issue by jskeet** [cincuranet/ConfigureAwaitChecker#5]
The analyzer has been working very well for me, and there's nothing obvious that needs doing to it.

I'm mentioning it in C# in Depth, and I suspect that some readers may be nervous of a beta package - any reason not to do a production release?

**Comment by cincuranet** [comment]
I don't know honestly. I recall having some plans for improvements, but I don't remember the details anymore. I suppose that can wait for v2 anyway. I'll build a 1.0.0 now and publish it.

Stoked to have this small piece of code mentioned in your - famous - book.

**Comment by cincuranet** [comment]
Alright. [The 1.0.0 is out](https://www.nuget.org/packages/ConfigureAwaitChecker.Analyzer/1.0.0). I tried to update some packages too. Sadly going straight to the latest version didn't work, so I updated manually to the point where it was still working from the get go. If you spot some packages that could still be updated, let me know.

**Comment by jskeet** [comment]
Woot - thanks very much :)
