### ISSUE TITLE
After adding this analyzer to a single project, it appears in all projects of the solution

### ISSUE THREAD

**Issue by ursenzler** [cincuranet/ConfigureAwaitChecker#7]
I added this analyzer over NuGet to a couple of projects in my solution. However, Visual Studio 2017 shows the analyzer in every project. I don't want to check for missing ConfigureAwaits in test projects, so it's annoying.

Do you have an idea what could cause this behavior?

**Comment by cincuranet** [comment]
Hmm, I'll try it and we will see.

**Comment by cincuranet** [comment]
I can't replicate this. This is what I get with solution with one _Class Library_ (analyzer here) and one _Console App_.
![img](https://user-images.githubusercontent.com/4540597/34512944-c3162832-f065-11e7-8cc9-c216e4d4ebfb.png)

My VS version is:
```
Microsoft Visual Studio Professional 2017 
Version 15.5.2
VisualStudio.15.Release/15.5.2+27130.2010
```

In fact the analyzer is called by VS, I'm not doing anything in this regard. So this is bit confusing how it could have happened.

**Comment by ursenzler** [comment]
Hmm, I'll try another solution and another computer. Will report back next week.

**Comment by peranborkett** [comment]
Are you referencing the projects you originally added the analyser to?
Setting PrivateAssets as below may help

    <PackageReference Include="ConfigureAwaitChecker.Analyzer" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

**Comment by cincuranet** [comment]
Interesting. because `PrivateAssets` has default value of `contentfiles;analyzers;build` (at least based on [this docs](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)).

**Comment by ursenzler** [comment]
I tried it with a new solution:

1. added two .net Standard Projects targeting .net47
1. added a reference from the second project to the first one
1. add the analyzer to the first one

The result is that the analyzer is listed in the second project, too:
![image](https://user-images.githubusercontent.com/287565/34670878-6a48e804-f478-11e7-8fc6-be13723df0ee.png)

After adding PrivateAssets as suggested by @peranborkett it looks like:
![image](https://user-images.githubusercontent.com/287565/34670934-a52924c0-f478-11e7-86bc-4212c92b163f.png)

So adding the `PrivateAssets` solves my problem. However, I'm surprised that analyzers are not "private" by default.

Thanks to both of you.
