### ISSUE TITLE
Can't fix missing ConfigureAwait, when result of await is an argument of a method

### ISSUE THREAD

**Issue by ursenzler** [cincuranet/ConfigureAwaitChecker#8]
It seems that the QuickFix is not possible when the await is an argument of a method call.

Something like this:

`foo.Bar(await x.Get());`

But I'm not sure whether this happens all the time. Just found out when using your analyzer in my code.

Thanks a lot for this analyzer!

**Comment by cincuranet** [comment]
OK, the commit ada3bf662bec22173cb93893261ccb832eb3403d should fix it. I'll publish 1.0.1 on NuGet shortly.

**Comment by ursenzler** [comment]
Thanks!
