### ISSUE TITLE
Fix for the Task.Yield()

### ISSUE THREAD

**Issue by AgentFire** [cincuranet/ConfigureAwaitChecker#9]
**ConfigureAwaitChecker** thinks `await Task.Yield();` instruction is obligated to be Configure-Awaited:
![](https://i.snag.gy/khBJTZ.jpg)

Yet it is not, since the `Task.Yield`'s result is not a `Task` and hence doesn't even have the method. Nor does it need the context switch option.

Please, fix the non-task `ConfigureAwait` rule.

**Comment by cincuranet** [comment]
True. I'll check that out.

**Comment by AgentFire** [comment]
Fix any soon? :)

**Comment by cincuranet** [comment]
Not really sure. :) I'm quite busy at the moment.

**Comment by cincuranet** [comment]
Done in 3a3c1a38c2d9ce1a52e5121a8164fdfd83409eab.
